# NumPyサンプルプログラム

In [1]:
import numpy as np

In [2]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


ここで変数aの3x3の行列の要素に、それぞれ1を加える。

In [3]:
b = a + 1
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


以降、行列の演算を実行する。

In [4]:
a - b

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [5]:
a + b

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [6]:
a * b

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [7]:
a / b

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [8]:
a + b.T

array([[ 1,  5,  9],
       [ 5,  9, 13],
       [ 9, 13, 17]])